CREATE DATABASE MoviePass;

USE MoviePass;

create table Users(
    ID_User INT NOT NULL PRIMARY KEY,
    firstName NOT NULL VARCHAR(30),
    lastName NOT NULL VARCHAR(30),
    dni INT NOT NULL INTEGER,
    email, NOT NULL INTEGER(30),
    pass NOT NULL VARCHAR(45)
);

-- REVISAR POR QUE EL CODIGO HECHO POR EL PROFESOR ES DIFERENTE Y USA OTRAS REGLAS PARA CREAR LA BS A DIFERENCIA DE COMO LO HACEMOS NOSOTROS EN LA CURSADA DE BS. 

